### PR TITLE
Update in line with latest 3.0 cookiecutter, use PEP8 package name

### PR DESCRIPTION
**Pull request by krassowski**
## What's new

- use PEP8-compatible package name (dashes not underscores), as mentioned in #118
- update in line with latest 3.0 cookiecutter
  - migrates to `pathlib`
  - adds `install.json` for uninstall instruction from JupyterLab UI
  - updates the installation instructions which were incorrect for 3.0 (Node.js not is need for 3.x, build step not needed)
  - adds missing uninstall installation for 3.x
- fixes uninstall instruction formatting in docs

### CODE REVIEW

**Comment by krassowski** [comment]
Ready for review @cameron-toy, @juliahuynh.

**Comment by cameron-toy** [comment]
@hbcarlos I remember you changed the package name from dashes to underscores for some reason, do you remember why? If it was just a stylistic change I'm going to merge this pr for PEP8 compliance.

**Comment by hbcarlos** [comment]
Yep, was an [issue](https://github.com/jupyterlab/jupyterlab/pull/9655) (solved now) on Jupiter lab.

**Comment by hbcarlos** [comment]
You can merge. Should work now.

**Pull request merged**
